### User sign up endpoint
POST  http://localhost:3001/v1/user
Content-Type: application/json

{
"name": "Mariko",
  "company": "xTT inc",
  "address": "15 Jay St, Quincy, GA",
  "phone": "212547621",
  "email": "mariko15@gmail.com",
  "password": "admin123"
	
}


### User log in endpoint
POST  http://localhost:3001/v1/user/login
Content-Type: application/json

{
  "email": "mariko15@gmail.com",
  "password": "admin"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlrbzE1QGdtYWlsLmNvbSIsImlhdCI6MTYxNjAyNDc0NSwiZXhwIjoxNjE2MTExMTQ1fQ.qbTdp2LG7GEGbPkaNdi_TghSiQqsjoHycLOAMj229vc
   

### Get token
GET http://localhost:3001/v1/tokens/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlrbzE1QGdtYWlsLmNvbSIsImlhdCI6MTYxNTQyNzEwMSwiZXhwIjoxNjE1NTEzNTAxfQ.MReOJieQtXhPSMSc-OQgJP8s7Rk9LaK3_vzLc4lMHak

###
POST  http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
  "email": "mariko15@gmail.com"
}


### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6I…TQ1fQ.qbTdp2LG7GEGbPkaNdi_TghSiQqsjoHycLOAMj229vc



### Create ticket
POST http://localhost:3001/v1/ticket/
Content-Type: application/json

{
	"subject": "Client failed to communicate",
	"sender": "Thang",
	
  "message": "Unfulfilled"
}

