### User sign up endpoint
POST  http://localhost:3001/v1/user
Content-Type: application/json

{
"name": "Mariko",
  "company": "xTT inc",
  "address": "15 Jay St, Quincy, GA",
  "phone": "212547621",
  "email": "mariko15@gmail.com",
  "password": "admin123"
	
}


### User log in endpoint
POST  http://localhost:3001/v1/user/login
Content-Type: application/json

{
  "email": "mariko15@gmail.com",
  "password": "admin"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlrbzE1QGdtYWlsLmNvbSIsImlhdCI6MTYxNTQyNzAyNSwiZXhwIjoxNjE1NTEzNDI1fQ.46CaZJtQG8TzvATmOW4-0Gm9e_XqROY7CFL4vBWAVXY

### Get token
GET http://localhost:3001/v1/tokens/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlrbzE1QGdtYWlsLmNvbSIsImlhdCI6MTYxNTQyNzEwMSwiZXhwIjoxNjE1NTEzNTAxfQ.MReOJieQtXhPSMSc-OQgJP8s7Rk9LaK3_vzLc4lMHak

###
POST  http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
  "email": "mariko15@gmail.com"
}


### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmlrbzE1QGdtYWlsLmNvbSIsImlhdCI6MTYxNTUxMjE2MCwiZXhwIjoxNjE1NTk4NTYwfQ.JbQSGCftU_2KBDQj3UtweKLWeeGMYn1Mnw9-UgEeU4c



### Create ticket
POST http://localhost:3001/v1/ticket/
Content-Type: application/json

{
	"subject": "Cannot get API",
	"sender": "Thang",
	"message": "I want to learn to learn to learn"
}

